# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np

In [2]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)

In [3]:
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [4]:
minutes_column = data[:, 1]
ingredients_column = data[:, 2]

In [5]:
print(np.average(minutes_column))
print(np.average(ingredients_column))

21601.00169
9.05528


In [6]:
print(np.amin(minutes_column))
print(np.amin(ingredients_column))

0
1


In [7]:
print(np.amax(minutes_column))
print(np.amax(ingredients_column))

2147483647
39


In [8]:
print(np.median(minutes_column))
print(np.median(ingredients_column))

40.0
9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [9]:
q = np.quantile(data[:, 1], 0.75)
print(q)
data[:, 1] = data[:, 1].clip(max=q)
print(data)

65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
minutes = data[:, 1]
print(np.sum(minutes==0))    # узнаем количество имеющихся нулей
data[:, 1] = np.where(minutes==0, 1, data[:, 1])    # заменим нули на единицы
print(np.sum(minutes==0))    # убедимся, что количество нулей изменилось

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
unique_data = np.unique(data[:, 0])    # проверка уникальности будет проводиться по полю id
rows = data.shape[0]
unique_rows = unique_data.shape[0]
print(rows)    # всего
print(unique_rows)    # уникальных

100000
100000


numpy-1.24.2
6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [12]:
unique_ingredients = np.unique(data[:, 2])
print(unique_ingredients.shape[0])
print(unique_ingredients)

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [13]:
short_version = data[(data[:, 2] <= 5)]
print(short_version)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [15]:
res = data[:, 2] / data[:, 1]
print(res)
print(np.amax(res))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [16]:
sorted_data = data[data[:, 1].argsort()[::-1]]
top100 = sorted_data[:100]
print(np.average(top100[:, 2]))

9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [17]:
print(data[np.random.choice(data.shape[0], 10)])

[[ 35426     15      5]
 [ 25322     18      4]
 [235316     60      7]
 [179796     20      9]
 [ 59273     35      8]
 [ 36083     27     11]
 [277414     20     10]
 [239773     50      8]
 [165969     22      9]
 [366313     35     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [18]:
ingredients = data[:, 2]
average_ingredients = np.average(ingredients)
print(data[ingredients < average_ingredients].shape[0] )

58802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [19]:
easy = ((data[:, 1] <= 20) & (data[:, 2] <= 5))
last_column = np.where(easy, 1, 0)
easy_version = np.insert(data, 3, last_column, axis=1)
print(easy_version)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [20]:
print(np.average(easy_version[:, 3]) * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [21]:
short = data[:, 1] < 10
standard = (data[:, 1] >= 10) & (data[:, 1] < 20)
long = data[:, 1] >= 20

min_group_length = min(len(data[short]), len(data[standard]), len(data[long]))

short_group = data[short][:min_group_length]
standard_group = data[standard][:min_group_length]
long_group = data[long][:min_group_length]

array_3d = np.array([short_group, standard_group, long_group])
print(array_3d.shape)    # форма массива
print(array_3d)    # сам массив

(3, 7588, 3)
[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
